apiVersion: v1
kind: Service
metadata:
    annotations:
        service.beta.kubernetes.io/notfightclubangular-resource-group: p3_fight_club
    name: notfightclubangular
spec:
    loadBalancerIP: 20.102.0.170
    type: LoadBalancer
    ports:
    - port: 80
    selector:
        app: notfightclubangular